parameters:
- name: jobName
  type: string
  default: BicepEnvironmentValidation
- name: dependsOn
  type: object
  default: []
- name: azureSubscription
  type: string
- name: environmentTag
  type: string
- name: environment
  type: string

jobs:
- deployment: ValidateBicepAgainst${{ parameters.environmentTag }}Environment
  dependsOn: ${{ parameters.dependsOn }}
  environment: ${{ parameters.environment }}

  workspace:
    clean: all

  variables:
    environmentTagLower: ${{ lower(parameters.environmentTag) }}

  strategy:
    runOnce:
      deploy:
        steps:
          - checkout: self

          - task: AzureCLI@2
            name: RunPreflightValidation
            inputs:
              azureSubscription: ${{ parameters.azureSubscription }}
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment sub validate `
                  --template-file bicep/platform.bicep `
                  --location 'uksouth' `
                  --parameters @params/platform.${{ parameters.environmentTagLower }}.json

                if ((az group exists --name 'rg-mxconsulting-${{ parameters.environmentTagLower }}-uksouth') -eq $true) { 
                  Write-Host "Performing az deployment group validation as 'rg-mxconsulting-${{ parameters.environmentTagLower }}-uksouth' exists"
                  az deployment group validate `
                    --resource-group 'rg-mxconsulting-${{ parameters.environmentTagLower }}-uksouth' `
                    --template-file $(Build.sourcesDirectory)/bicep/services.bicep `
                    --parameters @$(Build.sourcesDirectory)/params/services.${{ parameters.environmentTagLower }}.json
                }

          - task: AzureCLI@2
            name: RunWhatIfDeploy
            inputs:
              azureSubscription: ${{ parameters.azureSubscription }}
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment sub what-if `
                  --template-file bicep/platform.bicep `
                  --location 'uksouth' `
                  --parameters @params/platform.${{ parameters.environmentTagLower }}.json

                if ((az group exists --name 'rg-mxconsulting-${{ parameters.environmentTagLower }}-uksouth') -eq $true) { 
                  Write-Host "Performing az deployment group validation as 'rg-mxconsulting-${{ parameters.environmentTagLower }}-uksouth' exists"
                  az deployment group what-if `
                    --resource-group 'rg-mxconsulting-${{ parameters.environmentTagLower }}-uksouth' `
                    --template-file $(Build.sourcesDirectory)/bicep/services.bicep `
                    --parameters @$(Build.sourcesDirectory)/params/services.${{ parameters.environmentTagLower }}.json
                }
