parameters:
- name: azureSubscription
  type: string
- name: environment
  type: string
- name: environmentName
  type: string
- name: environmentTag
  type: string
- name: webAppsAzureSubscription
  type: string
- name: webAppsEnvironment
  type: string
- name: webAppsResourceGroup
  type: string


stages:
- stage: Deploy${{ parameters.environmentName }}

  jobs:
  - deployment: Deploy${{ parameters.environmentName }}PlatformBicep
    environment: ${{ parameters.environment }}

    workspace:
      clean: all

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: AzureCLI@2
              displayName: Deploy${{ parameters.environmentName }}PlatformBicep
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  if ($null -eq (az keyvault show --name 'kv-mxcon-${{ parameters.environmentTag }}-uksouth')) { $keyVaultCreateMode = 'default' } else { $keyVaultCreateMode = 'recover' }

                  az deployment sub create `
                    --template-file bicep/platform.bicep `
                    --location 'uksouth' `
                    --parameters @params/platform.${{ parameters.environmentTag }}.json `
                      parKeyVaultCreateMode=$keyVaultCreateMode

  - deployment: Deploy${{ parameters.environmentName }}ServicesBicep
    dependsOn: ['Deploy${{ parameters.environmentName }}PlatformBicep']
    environment: ${{ parameters.environment }}

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            
            - task: AzureCLI@2
              displayName: Deploy${{ parameters.environmentName }}ServicesBicep
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az deployment group create `
                    --resource-group 'rg-mxconsulting-${{ parameters.environmentTag }}-uksouth' `
                    --template-file bicep/services.bicep `
                    --parameters @params/services.${{ parameters.environmentTag }}.json

  - template: jobs/deploy-web-app.yml@ado-pipeline-templates
    parameters:
      dependsOn: ['Deploy${{ parameters.environmentName }}ServicesBicep']
      environment: ${{ parameters.webAppsEnvironment }}
      projectName: mx-webapp
      jobName: DeployWebApp
      webAppName: 'webapp-mxconsulting-${{ parameters.environmentTag }}-uksouth'
      webAppNameResourceGroup: ${{ parameters.webAppsResourceGroup }}
      subscription: ${{ parameters.webAppsAzureSubscription }}
