parameters:
- name: azureSubscription
  type: string
- name: webAppsAzureSubscription
  type: string
- name: environmentTag
  type: string
- name: environment
  type: string

stages:
- stage: Deploy${{ parameters.environmentTag }}

  variables:
    environmentTagLower: ${{ lower(parameters.environmentTag) }}

  jobs:
  - deployment: Deploy${{ parameters.environmentTag }}PlatformBicep
    environment: ${{ parameters.environment }}

    workspace:
      clean: all

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: AzureCLI@2
              displayName: Deploy${{ parameters.environmentTag }}PlatformBicep
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az deployment sub create `
                    --template-file bicep/platform.bicep `
                    --location 'uksouth' `
                    --parameters @params/platform.$(environmentTagLower).json

  - deployment: Deploy${{ parameters.environmentTag }}ServicesBicep
    dependsOn: ['Deploy${{ parameters.environmentTag }}PlatformBicep']
    environment: ${{ parameters.environment }}

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            
            - task: AzureCLI@2
              displayName: Deploy${{ parameters.environmentTag }}ServicesBicep
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az deployment group create `
                    --resource-group 'rg-mxconsulting-$(environmentTagLower)-uksouth' `
                    --template-file bicep/services.bicep `
                    --parameters @params/services.$(environmentTagLower).json

  - template: jobs/deploy-web-app.yml@ado-pipeline-templates
    parameters:
      dependsOn: ['Deploy${{ parameters.environmentTag }}ServicesBicep']
      environment: 'platform-webapps-$(environmentTagLower)-uksouth'
      projectName: mx-webapp
      jobName: DeployWebApp
      webAppName: 'webapp-mxconsulting-$(environmentTagLower)-uksouth'
      webAppNameResourceGroup: 'rg-platform-webapps-$(environmentTagLower)-uksouth'
      subscription: ${{ parameters.webAppsAzureSubscription }}
