trigger: none

pool: 'Dedicated'

resources:
  pipelines:
  - pipeline: mx-consulting-web.Validate
    source: mx-consulting-web.Validate
    trigger: true

stages: 
- stage: Build
  jobs:
  - template: templates/build-web-app.yml
    parameters: 
      jobName: 'BuildPublicWebApp'
      projectName: 'mx-webapp'
      publishArtifact: true

- stage: DeployPrdPlatform
  jobs:
  - job: DeployPrdPlatformBicep
    steps:
      - task: AzureCLI@2
        displayName: DeployPrdPlatformBicep
        inputs:
          azureSubscription: 'spn-ado-Personal-Public-mx-consulting-prd'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment sub create `
              --template-file bicep/platform.bicep `
              --location 'uksouth' `
              --parameters @params/platform.prd.json

- stage: DeployPrdServices
  jobs:
  - job: DeployPrdServicesBicep
    steps:
      - task: AzureCLI@2
        displayName: DeployPrdServicesBicep
        inputs:
          azureSubscription: 'spn-ado-Personal-Public-mx-consulting-prd'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment group create `
              --resource-group 'rg-mxconsulting-prd-uksouth' `
              --template-file bicep/services.bicep `
              --parameters @params/services.prd.json

  - template: templates/deploy-web-app.yml
    parameters:
      dependsOn: ['DeployPrdServicesBicep']
      projectName: mx-webapp
      jobName: DeployWebApp
      webAppName: 'webapp-mxconsulting-prd-uksouth'
      webAppNameResourceGroup: 'rg-platform-webapps-prd-uksouth'
      subscription: 'spn-ado-Personal-Public-mx-consulting-prd-webapps'
