trigger: none
pr: none

pool: 'Dedicated'

resources:
  repositories:
    - repository: ado-pipeline-templates
      type: github
      name: frasermolyneux/ado-pipeline-templates
      endpoint: github.com_frasermolyneux
  pipelines:
  - pipeline: mx-consulting-web.Validate
    source: mx-consulting-web.Validate
    trigger:
      branches:
        include:
        - main

stages: 
- stage: Build
  jobs:
  - template: jobs/build-web-app.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BuildWebApp'
      projectName: 'mx-webapp'
      publishArtifact: true

- stage: DeployPrdPlatform
  jobs:

  - deployment: DeployPrdPlatformBicep
    environment: 'mx-consulting-prd'

    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureCLI@2
              displayName: DeployPrdPlatformBicep
              inputs:
                azureSubscription: 'spn-ado-Personal-Public-mx-consulting-prd'
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az deployment sub create `
                    --template-file bicep/platform.bicep `
                    --location 'uksouth' `
                    --parameters @params/platform.prd.json

- stage: DeployPrdServices
  jobs:

  - deployment: DeployPrdServicesBicep
    environment: 'mx-consulting-prd'

    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureCLI@2
              displayName: DeployPrdServicesBicep
              inputs:
                azureSubscription: 'spn-ado-Personal-Public-mx-consulting-prd'
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az deployment group create `
                    --resource-group 'rg-mxconsulting-prd-uksouth' `
                    --template-file bicep/services.bicep `
                    --parameters @params/services.prd.json

  - template: jobs/deploy-web-app.yml@ado-pipeline-templates
    parameters:
      dependsOn: ['DeployPrdServicesBicep']
      environment: 'platform-webapps-prd-uksouth'
      projectName: mx-webapp
      jobName: DeployWebApp
      webAppName: 'webapp-mxconsulting-prd-uksouth'
      webAppNameResourceGroup: 'rg-platform-webapps-prd-uksouth'
      subscription: 'spn-ado-Personal-Public-mx-consulting-prd-webapps'
